image: java:8

pipelines:
  tags:
    v*:
      - step:
          caches:
            - gradle
          script:
            - bash ./gradlew build 
            - mv build/distributions/*.zip build/distributions/pxWorlds-${BITBUCKET_TAG}.zip
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build/distributions/pxWorlds-${BITBUCKET_TAG}.zip"
